animal: mouse
bin_size: 60
threads: 6
verbose: false
validation: true
identifier: true
classifier: true
min_contrast_db: 3.0
nfft: 1024
window_type: hamming
window_size: 256
noverlap: 128
lower_frequency_cutoff: 45000
higher_frequency_cutoff: 125000
min_vocal_duration_frames: 5
max_vocal_duration_frames: 250
